---
name: Proposal
description: Propose an enhancement or new feature.
labels:
  - proposal
body:
  - type: textarea
    id: change
    attributes:
      label: Proposed change
      description: This could be to support new features of existing modules, add new modules that conform to the fission mode,etc.
    validations:
      required: true
  - type: textarea
    id: usecase
    attributes:
      label: Use case
      description: What is the use case or general motivation for this proposal?
    validations:
      required: true
  - type: textarea
    id: contribute
    attributes:
      label: Contribution
      description: |-
        Are you intending or interested in contributing code for this proposal if accepted?
    validations:
      required: false